import re
from pathlib import Path

from ..domain.planning import action_for
from ..skills.safety import suspicious_files
from ..skills.snapshot import files as snapshot_files
from .client import GitHub, UploadError


def _safe_component(value):
    value = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip().lower()).strip(".-")
    if not value: raise UploadError("agent name/category/skill ID cannot be empty")
    return value


def upload_skill(repo, agent_name, skill_id, skill_path, force=False, source_profile="active", command="", remove=False):
    parts = skill_id.split("/", 1)
    if len(parts) != 2: raise UploadError("skill ID must include category/skill")
    category, short_id = (_safe_component(x) for x in parts)
    agent = _safe_component(agent_name)
    try: local = {} if remove else snapshot_files(Path(skill_path))
    except RuntimeError as exc: raise UploadError(str(exc)) from exc
    suspicious = suspicious_files(local)
    if suspicious and not force: raise UploadError("possible secret files detected; use --force to confirm: " + ", ".join(suspicious))

    gh = GitHub(repo)
    base = gh.default_branch()
    branch = f"ugh-cloud/agents/{agent}/skills/{category}/{short_id}"
    target = f"agents/{agent}/skills/{category}/{short_id}"
    existing = gh.find_pull(branch)
    parent = None
    pr_url = None
    previous_url = None
    if existing and (existing.get("state") == "closed" or existing.get("merged_at") is not None):
        previous_url = existing.get("html_url")
        suffix = 2
        candidate = f"{branch}-{suffix}"
        while gh.ref_exists(candidate): suffix += 1; candidate = f"{branch}-{suffix}"
        branch, existing = candidate, None
    elif not existing and gh.ref_exists(branch):
        suffix = 2
        candidate = f"{branch}-{suffix}"
        while gh.ref_exists(candidate): suffix += 1; candidate = f"{branch}-{suffix}"
        branch = candidate
    if existing:
        parent = existing["head"]["sha"]
        pr_url = existing.get("html_url")
        remote = gh.git_data.remote_files(parent, target)
    else:
        try: base_ref = gh.ref(base)
        except UploadError as exc:
            if "Git Repository is empty" not in str(exc): raise
            base_ref = gh.initialize_branch(base)
        parent = base_ref["object"]["sha"]
        remote = gh.git_data.remote_files(parent, target)
    action = action_for(local, remote)
    if action is None: return {"skill": skill_id, "action": "noop", "status": "success", "message": "remote content is identical", "pr_url": pr_url}

    entries = []
    for name in sorted(set(local) | set(remote)):
        path = f"{target}/{name}"
        if name not in local: entries.append({"path": path, "mode": "100644", "type": "blob", "sha": None})
        else: entries.append({"path": path, "mode": "100644", "type": "blob", "sha": gh.blob(local[name])})
    base_tree = gh.commit(parent)["tree"]["sha"]
    tree = gh.create_tree(base_tree, entries)
    commit = gh.create_commit(f"chore({agent}): {action} skill {short_id}", tree, parent)
    if not existing: gh.create_ref(branch, parent)
    gh.update_ref(branch, commit)
    display = agent_name.strip() or agent
    if display.islower(): display = display.title()
    title = f"[{display}] Request to {action} skill `{short_id}`"
    body = "\n".join([f"Source profile: {source_profile}", f"Target agent: {display}", f"Skill: {skill_id}", f"Action: {action}", f"Command: /ugh {command}", "", "Files:", *[f"- {n}" for n in sorted(local)], "", "Generated by: ugh-cloud", f"Force upload: {'yes' if force else 'no'}"])
    if suspicious: body += "\n\nForce warnings acknowledged for:\n" + "\n".join(f"- {n}" for n in suspicious)
    if previous_url: body += f"\n\nPrevious closed PR: {previous_url}"
    if pr_url: return {"skill": skill_id, "action": action, "status": "updated", "pr_url": pr_url, "branch": branch}
    pull = gh.create_pull(title, body, branch, base)
    return {"skill": skill_id, "action": action, "status": "created", "pr_url": pull.get("html_url"), "branch": branch}
